version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  common:
    image: l2py_common
    build:
      context: ./common
  data:
    build:
      context: ./data
    restart: always
    environment:
      MONGO_URI: mongo

  login:
    build:
      context: ./login
    restart: always
    environment:
      MONGO_URI: mongo
    ports:
      - 2106:2106

  game:
    build:
      context: ./game
    restart: always
    environment:
      LOGIN_SERVER_API_HOST: login
      MONGO_URI: mongo
      SERVER_ID: 1
    ports:
      - 7777:7777
